[
    {
        "url": "https://api.github.com/repos/haruiz/CvStudio/issues/12",
        "repository_url": "https://api.github.com/repos/haruiz/CvStudio",
        "labels_url": "https://api.github.com/repos/haruiz/CvStudio/issues/12/labels{/name}",
        "comments_url": "https://api.github.com/repos/haruiz/CvStudio/issues/12/comments",
        "events_url": "https://api.github.com/repos/haruiz/CvStudio/issues/12/events",
        "html_url": "https://github.com/haruiz/CvStudio/issues/12",
        "id": 516719968,
        "node_id": "MDU6SXNzdWU1MTY3MTk5Njg=",
        "number": 12,
        "title": "testing on linux",
        "user": {
            "login": "epifanio",
            "id": 18949,
            "node_id": "MDQ6VXNlcjE4OTQ5",
            "avatar_url": "https://avatars0.githubusercontent.com/u/18949?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/epifanio",
            "html_url": "https://github.com/epifanio",
            "followers_url": "https://api.github.com/users/epifanio/followers",
            "following_url": "https://api.github.com/users/epifanio/following{/other_user}",
            "gists_url": "https://api.github.com/users/epifanio/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/epifanio/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/epifanio/subscriptions",
            "organizations_url": "https://api.github.com/users/epifanio/orgs",
            "repos_url": "https://api.github.com/users/epifanio/repos",
            "events_url": "https://api.github.com/users/epifanio/events{/privacy}",
            "received_events_url": "https://api.github.com/users/epifanio/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1559572521,
                "node_id": "MDU6TGFiZWwxNTU5NTcyNTIx",
                "url": "https://api.github.com/repos/haruiz/CvStudio/labels/bug",
                "name": "bug",
                "color": "d73a4a",
                "default": true,
                "description": "Something isn't working"
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "haruiz",
            "id": 3827551,
            "node_id": "MDQ6VXNlcjM4Mjc1NTE=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3827551?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/haruiz",
            "html_url": "https://github.com/haruiz",
            "followers_url": "https://api.github.com/users/haruiz/followers",
            "following_url": "https://api.github.com/users/haruiz/following{/other_user}",
            "gists_url": "https://api.github.com/users/haruiz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/haruiz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/haruiz/subscriptions",
            "organizations_url": "https://api.github.com/users/haruiz/orgs",
            "repos_url": "https://api.github.com/users/haruiz/repos",
            "events_url": "https://api.github.com/users/haruiz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/haruiz/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "haruiz",
                "id": 3827551,
                "node_id": "MDQ6VXNlcjM4Mjc1NTE=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/3827551?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/haruiz",
                "html_url": "https://github.com/haruiz",
                "followers_url": "https://api.github.com/users/haruiz/followers",
                "following_url": "https://api.github.com/users/haruiz/following{/other_user}",
                "gists_url": "https://api.github.com/users/haruiz/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/haruiz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/haruiz/subscriptions",
                "organizations_url": "https://api.github.com/users/haruiz/orgs",
                "repos_url": "https://api.github.com/users/haruiz/repos",
                "events_url": "https://api.github.com/users/haruiz/events{/privacy}",
                "received_events_url": "https://api.github.com/users/haruiz/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 3,
        "created_at": "2019-11-02T20:59:36Z",
        "updated_at": "2019-11-04T04:14:03Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Hi, I was trying out this new app (Thanks!) on a Linux environment, using the system python that ships with it.\r\n\r\nI only modified the [pip_req.txt](https://github.com/haruiz/CvStudio/blob/master/pip_req.txt) by removing the forced versions for some of the dependencies (so to don't replace libraries I already have installed) I then make sure I had the other dependencies (torch etc.) were installed correctly.\r\n\r\nMy pipreq.txt looks like:\r\n\r\n```\r\ncertifi==2019.6.16\r\ncffi==1.12.3\r\ndask\r\nhurry.filesize==0.9\r\nimutils==0.5.3\r\nmore-itertools==7.2.0\r\nnumpy==1.17.2\r\nolefile==0.46\r\nopencv-contrib-python\r\npeewee==3.10.0\r\nPillow\r\npycparser==2.19\r\npyface==6.1.2\r\nPyQt5\r\nPyQt5\r\n#PyQt5Designer\r\nsix==1.12.0\r\ntoolz==0.10.0\r\ntraits==5.1.2\r\nwincertstore==0.2\r\nmarshmallow==3.2.0\r\n```\r\nNote I didn't find a package for `PyQt5Designer`\r\n\r\n```\r\nepinux@epinux:~$ pip3 install PyQt5Designer\r\nERROR: Could not find a version that satisfies the requirement PyQt5Designer (from versions: none)\r\nERROR: No matching distribution found for PyQt5Designer\r\nepinux@epinux:~$ pip3 install PyQt5Designer==5.10.1\r\nERROR: Could not find a version that satisfies the requirement PyQt5Designer==5.10.1 (from versions: none)\r\nERROR: No matching distribution found for PyQt5Designer==5.10.1\r\nepinux@epinux:~$ \r\n```\r\n\r\n\r\n\r\nTring to run the app I noticed some differences from the video, in my case there are no \"menu-actions\" in the lower-left side of the application toolbar, and I was not able to understand how load images into the app. Here a quick record of my desktop trying to run the app:  https://epinux.com/index.php/s/5TTQSDw6Y79DHYK \r\n\r\n\r\nDo you have any hints on how to debug this issue?\r\n\r\nI don't know if useful, but from trying to click on some of the links below the dataset folder icon, I got the following error log:\r\n\r\n```\r\npython3 cvstudio.py \r\nlibpng warning: iCCP: known incorrect sRGB profile\r\nAttributeError: __getattribute__\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_datasets.py\", line 177, in open_dataset_action_slot\r\n    tab_widget = MediaTabWidget(vo)\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_media.py\", line 21, in __init__\r\n    self.media_grid=Gallery()\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/gallery.py\", line 119, in __init__\r\n    self.setupUi(self)\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/base_gallery.py\", line 221, in setupUi\r\n    QtCore.QMetaObject.connectSlotsByName(Gallery)\r\nSystemError: <built-in function connectSlotsByName> returned a result with an error set\r\nAttributeError: __getattribute__\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_datasets.py\", line 177, in open_dataset_action_slot\r\n    tab_widget = MediaTabWidget(vo)\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/tab_media.py\", line 21, in __init__\r\n    self.media_grid=Gallery()\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/gallery.py\", line 119, in __init__\r\n    self.setupUi(self)\r\n  File \"/home/epinux/PycharmProjects/CvStudio/view/widgets/gallery/base_gallery.py\", line 221, in setupUi\r\n    QtCore.QMetaObject.connectSlotsByName(Gallery)\r\nSystemError: <built-in function connectSlotsByName> returned a result with an error set\r\nlibpng warning: iCCP: known incorrect sRGB profile\r\nlibpng warning: iCCP: known incorrect sRGB profile\r\nlibpng warning: iCCP: known incorrect sRGB profile\r\n```\r\n\r\n"
    }
]