[
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/568",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/568/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/568/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/568/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/568",
        "id": 562998614,
        "node_id": "MDU6SXNzdWU1NjI5OTg2MTQ=",
        "number": 568,
        "title": "UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize",
        "user": {
            "login": "josephkokchin",
            "id": 32803619,
            "node_id": "MDQ6VXNlcjMyODAzNjE5",
            "avatar_url": "https://avatars0.githubusercontent.com/u/32803619?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/josephkokchin",
            "html_url": "https://github.com/josephkokchin",
            "followers_url": "https://api.github.com/users/josephkokchin/followers",
            "following_url": "https://api.github.com/users/josephkokchin/following{/other_user}",
            "gists_url": "https://api.github.com/users/josephkokchin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/josephkokchin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/josephkokchin/subscriptions",
            "organizations_url": "https://api.github.com/users/josephkokchin/orgs",
            "repos_url": "https://api.github.com/users/josephkokchin/repos",
            "events_url": "https://api.github.com/users/josephkokchin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/josephkokchin/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-11T06:15:43Z",
        "updated_at": "2020-02-11T06:15:43Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Instructions for updating:\r\nColocations handled automatically by placer.\r\n---------------------------------------------------------------------------\r\nUnknownError                              Traceback (most recent call last)\r\n~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)\r\n   1333     try:\r\n-> 1334       return fn(*args)\r\n   1335     except errors.OpError as e:\r\n\r\n~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)\r\n   1318       return self._call_tf_sessionrun(\r\n-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)\r\n   1320 \r\n\r\n~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)\r\n   1406         self._session, options, feed_dict, fetch_list, target_list,\r\n-> 1407         run_metadata)\r\n   1408 \r\n\r\nUnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\r\n\t [[{{node TfPoseEstimator/MobilenetV2/Conv/Conv2D}}]]\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nUnknownError                              Traceback (most recent call last)\r\n<ipython-input-2-cb53a1a771ee> in <module>\r\n     12 \r\n     13 w, h = model_wh('0x0')\r\n---> 14 e = TfPoseEstimator(get_graph_path(\"mobilenet_v2_large\"), target_size=(1120, 720))\r\n     15 \r\n     16 while cap.isOpened():\r\n\r\n~/Projects/2020/Dahlsens/Source_Code/tf_pose/estimator.py in __init__(self, graph_path, target_size, tf_config)\r\n    352             feed_dict={\r\n    353                 self.tensor_image: [np.ndarray(shape=(target_size[1], target_size[0], 3), dtype=np.float32)],\r\n--> 354                 self.upsample_size: [target_size[1], target_size[0]]\r\n    355             }\r\n    356         )\r\n\r\n~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)\r\n    927     try:\r\n    928       result = self._run(None, fetches, feed_dict, options_ptr,\r\n--> 929                          run_metadata_ptr)\r\n    930       if run_metadata:\r\n    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)\r\n\r\n~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)\r\n   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):\r\n   1151       results = self._do_run(handle, final_targets, final_fetches,\r\n-> 1152                              feed_dict_tensor, options, run_metadata)\r\n   1153     else:\r\n   1154       results = []\r\n\r\n~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\r\n   1326     if handle is None:\r\n   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,\r\n-> 1328                            run_metadata)\r\n   1329     else:\r\n   1330       return self._do_call(_prun_fn, handle, feeds, fetches)\r\n\r\n~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)\r\n   1346           pass\r\n   1347       message = error_interpolation.interpolate(message, self._graph)\r\n-> 1348       raise type(e)(node_def, op, message)\r\n   1349 \r\n   1350   def _extend_graph(self):\r\n\r\nUnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\r\n\t [[node TfPoseEstimator/MobilenetV2/Conv/Conv2D (defined at /home/lauretta/Projects/2020/Dahlsens/Source_Code/tf_pose/estimator.py:315) ]]\r\n\r\nCaused by op 'TfPoseEstimator/MobilenetV2/Conv/Conv2D', defined at:\r\n  File \"/usr/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\r\n    app.launch_new_instance()\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/traitlets/config/application.py\", line 664, in launch_instance\r\n    app.start()\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 563, in start\r\n    self.io_loop.start()\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 148, in start\r\n    self.asyncio_loop.run_forever()\r\n  File \"/usr/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\r\n    self._run_once()\r\n  File \"/usr/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\r\n    handle._run()\r\n  File \"/usr/lib/python3.6/asyncio/events.py\", line 145, in _run\r\n    self._callback(*self._args)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/ioloop.py\", line 690, in <lambda>\r\n    lambda f: self._run_callback(functools.partial(callback, future))\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/ioloop.py\", line 743, in _run_callback\r\n    ret = callback()\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/gen.py\", line 787, in inner\r\n    self.run()\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/gen.py\", line 748, in run\r\n    yielded = self.gen.send(value)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\r\n    yield gen.maybe_future(dispatch(*args))\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\r\n    yielded = next(result)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\r\n    yield gen.maybe_future(handler(stream, idents, msg))\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\r\n    yielded = next(result)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\r\n    user_expressions, allow_stdin,\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\r\n    yielded = next(result)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\r\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\r\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2848, in run_cell\r\n    raw_cell, store_history, silent, shell_futures)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2874, in _run_cell\r\n    return runner(coro)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\r\n    coro.send(None)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell_async\r\n    interactivity=interactivity, compiler=compiler, result=result)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3242, in run_ast_nodes\r\n    if (await self.run_code(code, result,  async_=asy)):\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3319, in run_code\r\n    exec(code_obj, self.user_global_ns, self.user_ns)\r\n  File \"<ipython-input-2-cb53a1a771ee>\", line 14, in <module>\r\n    e = TfPoseEstimator(get_graph_path(\"mobilenet_v2_large\"), target_size=(1120, 720))\r\n  File \"/home/lauretta/Projects/2020/Dahlsens/Source_Code/tf_pose/estimator.py\", line 315, in __init__\r\n    tf.import_graph_def(graph_def, name='TfPoseEstimator')\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py\", line 507, in new_func\r\n    return func(*args, **kwargs)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py\", line 442, in import_graph_def\r\n    _ProcessNewOps(graph)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py\", line 235, in _ProcessNewOps\r\n    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 3433, in _add_new_tf_operations\r\n    for c_op in c_api_util.new_tf_operations(self)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 3433, in <listcomp>\r\n    for c_op in c_api_util.new_tf_operations(self)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 3325, in _create_op_from_tf_operation\r\n    ret = Operation(c_op, self)\r\n  File \"/home/lauretta/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 1801, in __init__\r\n    self._traceback = tf_stack.extract_stack()\r\n\r\nUnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\r\n\t [[node TfPoseEstimator/MobilenetV2/Conv/Conv2D (defined at /home/lauretta/Projects/2020/Dahlsens/Source_Code/tf_pose/estimator.py:315) ]]\r\n\r\n\r\nI have run into this when I try to run `TfPoseEstimator(get_graph_path(\"mobilenet_v2_large\"))`. Anyone has an idea how to resolve this ?"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/567",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/567/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/567/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/567/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/567",
        "id": 561885479,
        "node_id": "MDU6SXNzdWU1NjE4ODU0Nzk=",
        "number": 567,
        "title": "Preinstallation of Jeston case error on Mac OS",
        "user": {
            "login": "yijunmao",
            "id": 43157053,
            "node_id": "MDQ6VXNlcjQzMTU3MDUz",
            "avatar_url": "https://avatars1.githubusercontent.com/u/43157053?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yijunmao",
            "html_url": "https://github.com/yijunmao",
            "followers_url": "https://api.github.com/users/yijunmao/followers",
            "following_url": "https://api.github.com/users/yijunmao/following{/other_user}",
            "gists_url": "https://api.github.com/users/yijunmao/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yijunmao/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yijunmao/subscriptions",
            "organizations_url": "https://api.github.com/users/yijunmao/orgs",
            "repos_url": "https://api.github.com/users/yijunmao/repos",
            "events_url": "https://api.github.com/users/yijunmao/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yijunmao/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-07T21:38:22Z",
        "updated_at": "2020-02-07T21:38:22Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I'm trying to run tf_pose_estimation on my mac. But when trying to do pre installation of Jetson case, I got the following error:\r\n\r\n(tfpose) \u2718 myj@Yijuns-MacBook-Pro \ue0b0 ~/tf-pose-estimation \ue0b0 \ue0a0 master \u25cf \ue0b0 brew install libllvm-7-ocaml-dev libllvm7 llvm-7 llvm-7-dev llvm-7-doc llvm-7-examples llvm-7-runtime\r\nError: No available formula with the name \"libllvm-7-ocaml-dev\"\r\n==> Searching for a previously deleted formula (in the last month)...\r\nWarning: homebrew/core is shallow clone. To get complete history run:\r\ngit -C \"$(brew --repo homebrew/core)\" fetch --unshallow\r\n\r\nError: No previously deleted formula found.\r\n==> Searching for similarly named formulae...\r\nError: No similarly named formulae found.\r\n==> Searching taps...\r\n==> Searching taps on GitHub...\r\nError: No formulae found in taps.\r\n\r\nNot sure has anyone encountered similar issues previously and how did you solve that? Thx."
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/566",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/566/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/566/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/566/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/566",
        "id": 560212585,
        "node_id": "MDU6SXNzdWU1NjAyMTI1ODU=",
        "number": 566,
        "title": "How can I run many photos one time together?",
        "user": {
            "login": "Peterzz416",
            "id": 45709174,
            "node_id": "MDQ6VXNlcjQ1NzA5MTc0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/45709174?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Peterzz416",
            "html_url": "https://github.com/Peterzz416",
            "followers_url": "https://api.github.com/users/Peterzz416/followers",
            "following_url": "https://api.github.com/users/Peterzz416/following{/other_user}",
            "gists_url": "https://api.github.com/users/Peterzz416/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Peterzz416/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Peterzz416/subscriptions",
            "organizations_url": "https://api.github.com/users/Peterzz416/orgs",
            "repos_url": "https://api.github.com/users/Peterzz416/repos",
            "events_url": "https://api.github.com/users/Peterzz416/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Peterzz416/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-05T08:25:19Z",
        "updated_at": "2020-02-05T08:25:19Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I hope to run one time get many photos results, how can I achieve it by modifying code in run.py.THX"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/565",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/565/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/565/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/565/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/565",
        "id": 558871463,
        "node_id": "MDU6SXNzdWU1NTg4NzE0NjM=",
        "number": 565,
        "title": "training my own imgaes for mobile net giving an issue",
        "user": {
            "login": "vedphadke",
            "id": 42366040,
            "node_id": "MDQ6VXNlcjQyMzY2MDQw",
            "avatar_url": "https://avatars2.githubusercontent.com/u/42366040?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vedphadke",
            "html_url": "https://github.com/vedphadke",
            "followers_url": "https://api.github.com/users/vedphadke/followers",
            "following_url": "https://api.github.com/users/vedphadke/following{/other_user}",
            "gists_url": "https://api.github.com/users/vedphadke/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vedphadke/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vedphadke/subscriptions",
            "organizations_url": "https://api.github.com/users/vedphadke/orgs",
            "repos_url": "https://api.github.com/users/vedphadke/repos",
            "events_url": "https://api.github.com/users/vedphadke/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vedphadke/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-03T06:26:28Z",
        "updated_at": "2020-02-03T06:43:43Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I have some updated version of code which i wrote to train my dataset of 1040 images. while working on the mobilenet v2. Can anybody suggest me how can i train my own data set. As i'm new to tensorflow any help would be appreciated.\r\nIm using ubuntu 18.04\r\ngpu 1080\r\n"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/564",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/564/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/564/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/564/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/564",
        "id": 555164411,
        "node_id": "MDU6SXNzdWU1NTUxNjQ0MTE=",
        "number": 564,
        "title": "Does the code work on the Jetson Xavier?",
        "user": {
            "login": "duncanmix",
            "id": 55547989,
            "node_id": "MDQ6VXNlcjU1NTQ3OTg5",
            "avatar_url": "https://avatars0.githubusercontent.com/u/55547989?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/duncanmix",
            "html_url": "https://github.com/duncanmix",
            "followers_url": "https://api.github.com/users/duncanmix/followers",
            "following_url": "https://api.github.com/users/duncanmix/following{/other_user}",
            "gists_url": "https://api.github.com/users/duncanmix/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/duncanmix/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/duncanmix/subscriptions",
            "organizations_url": "https://api.github.com/users/duncanmix/orgs",
            "repos_url": "https://api.github.com/users/duncanmix/repos",
            "events_url": "https://api.github.com/users/duncanmix/events{/privacy}",
            "received_events_url": "https://api.github.com/users/duncanmix/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-01-26T01:38:11Z",
        "updated_at": "2020-01-26T01:38:11Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\r\nI am planning to buy the jetson xavier to see if there are improvements in speed"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/563",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/563/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/563/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/563/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/563",
        "id": 545015154,
        "node_id": "MDU6SXNzdWU1NDUwMTUxNTQ=",
        "number": 563,
        "title": "Random blue border added during training preprocessing",
        "user": {
            "login": "mgarbade",
            "id": 3956593,
            "node_id": "MDQ6VXNlcjM5NTY1OTM=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/3956593?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mgarbade",
            "html_url": "https://github.com/mgarbade",
            "followers_url": "https://api.github.com/users/mgarbade/followers",
            "following_url": "https://api.github.com/users/mgarbade/following{/other_user}",
            "gists_url": "https://api.github.com/users/mgarbade/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mgarbade/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mgarbade/subscriptions",
            "organizations_url": "https://api.github.com/users/mgarbade/orgs",
            "repos_url": "https://api.github.com/users/mgarbade/repos",
            "events_url": "https://api.github.com/users/mgarbade/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mgarbade/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-01-03T14:27:37Z",
        "updated_at": "2020-01-03T14:27:37Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "During training, a [random blue border](https://github.com/ildoonet/tf-pose-estimation/blob/master/tf_pose/pose_augment.py#L84-L90) is attached to every image in order to fit the target size criterion:\r\n\r\n```\r\n    if neww < _network_w or newh < _network_h:\r\n        pw = max(0, (_network_w - neww) // 2)\r\n        ph = max(0, (_network_h - newh) // 2)\r\n        mw = (_network_w - neww) % 2\r\n        mh = (_network_h - newh) % 2\r\n        color = random.randint(0, 255)\r\n        dst = cv2.copyMakeBorder(dst, ph, ph+mh, pw, pw+mw, cv2.BORDER_CONSTANT, value=(color, 0, 0))\r\n\r\n```\r\n![Screenshot from 2020-01-03 15-11-23](https://user-images.githubusercontent.com/3956593/71728104-7d1a1c00-2e3c-11ea-8fe7-97a29ac2d266.png)\r\n\r\nI assume the border should rather be filled with the value that is used for mean subtraction (127, 127, 127) or a random color, but random blue sounds wrong."
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/562",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/562/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/562/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/562/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/562",
        "id": 541923085,
        "node_id": "MDU6SXNzdWU1NDE5MjMwODU=",
        "number": 562,
        "title": "undeclared identifier 'PyString_Check'",
        "user": {
            "login": "d1Ng0",
            "id": 1245572,
            "node_id": "MDQ6VXNlcjEyNDU1NzI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1245572?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/d1Ng0",
            "html_url": "https://github.com/d1Ng0",
            "followers_url": "https://api.github.com/users/d1Ng0/followers",
            "following_url": "https://api.github.com/users/d1Ng0/following{/other_user}",
            "gists_url": "https://api.github.com/users/d1Ng0/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/d1Ng0/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/d1Ng0/subscriptions",
            "organizations_url": "https://api.github.com/users/d1Ng0/orgs",
            "repos_url": "https://api.github.com/users/d1Ng0/repos",
            "events_url": "https://api.github.com/users/d1Ng0/events{/privacy}",
            "received_events_url": "https://api.github.com/users/d1Ng0/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-12-23T22:31:40Z",
        "updated_at": "2020-01-07T05:58:32Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "My installation process crashes when attempting to use swig.\r\nI googled around and I found a tutorial that explains this is using the traditional python instead of python3. \r\n\r\nI am not clear what this installation step or how to fix it. Please help... \r\nMy configuration is Macbook Pro withouth dedicated GPU running Mojave 10.14.6 (18G103). I used anaconda to create an environment:\r\n\r\n`platform : osx-64\r\n             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6`\r\n\r\nThis is the error log:\r\n\r\n```\u21d2  swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace\r\nrunning build_ext\r\nbuilding '_pafprocess' extension\r\nswigging pafprocess.i to pafprocess_wrap.cpp\r\nswig -python -c++ -o pafprocess_wrap.cpp pafprocess.i\r\ncreating build\r\ncreating build/temp.macosx-10.14-x86_64-3.7\r\nclang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I. -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c pafprocess.cpp -o build/temp.macosx-10.14-x86_64-3.7/pafprocess.o\r\nclang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I. -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c pafprocess_wrap.cpp -o build/temp.macosx-10.14-x86_64-3.7/pafprocess_wrap.o\r\npafprocess_wrap.cpp:2226:11: warning: explicitly assigning value of variable of type 'int' to itself [-Wself-assign]\r\n                    res = SWIG_AddCast(res);\r\n                    ~~~ ^              ~~~\r\npafprocess_wrap.cpp:2229:11: warning: explicitly assigning value of variable of type 'int' to itself [-Wself-assign]\r\n                    res = SWIG_AddCast(res);\r\n                    ~~~ ^              ~~~\r\npafprocess_wrap.cpp:2528:22: warning: unused variable 'swig_empty_runtime_method_table' [-Wunused-variable]\r\n  static PyMethodDef swig_empty_runtime_method_table[] = { {NULL, NULL, 0, NULL} };/* Sentinel */\r\n                     ^\r\npafprocess_wrap.cpp:3066:9: error: use of undeclared identifier 'PyString_Check'; did you mean 'PyMapping_Check'?\r\n    if (PyString_Check(  py_obj)) return \"string\"      ;\r\n        ^~~~~~~~~~~~~~\r\n        PyMapping_Check\r\n/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m/abstract.h:1006:17: note: 'PyMapping_Check' declared here\r\nPyAPI_FUNC(int) PyMapping_Check(PyObject *o);\r\n                ^\r\npafprocess_wrap.cpp:4979:14: warning: explicitly assigning value of variable of type 'void *' to itself [-Wself-assign]\r\n  clientdata = clientdata;\r\n  ~~~~~~~~~~ ^ ~~~~~~~~~~\r\n4 warnings and 1 error generated.\r\nerror: command 'clang' failed with exit status 1```\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/561",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/561/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/561/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/561/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/pull/561",
        "id": 540891530,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzU1NjQyNzQx",
        "number": 561,
        "title": "fix import lru_cache",
        "user": {
            "login": "ysuzuki19",
            "id": 42496938,
            "node_id": "MDQ6VXNlcjQyNDk2OTM4",
            "avatar_url": "https://avatars0.githubusercontent.com/u/42496938?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ysuzuki19",
            "html_url": "https://github.com/ysuzuki19",
            "followers_url": "https://api.github.com/users/ysuzuki19/followers",
            "following_url": "https://api.github.com/users/ysuzuki19/following{/other_user}",
            "gists_url": "https://api.github.com/users/ysuzuki19/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ysuzuki19/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ysuzuki19/subscriptions",
            "organizations_url": "https://api.github.com/users/ysuzuki19/orgs",
            "repos_url": "https://api.github.com/users/ysuzuki19/repos",
            "events_url": "https://api.github.com/users/ysuzuki19/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ysuzuki19/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-20T09:35:42Z",
        "updated_at": "2019-12-20T09:35:42Z",
        "closed_at": null,
        "author_association": "NONE",
        "pull_request": {
            "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/pulls/561",
            "html_url": "https://github.com/ildoonet/tf-pose-estimation/pull/561",
            "diff_url": "https://github.com/ildoonet/tf-pose-estimation/pull/561.diff",
            "patch_url": "https://github.com/ildoonet/tf-pose-estimation/pull/561.patch"
        },
        "body": "When I want to execute run.py on python3 on macos, importError(lru_cache) was occurred.\r\nThis reference is following link.\r\n\r\nhttps://pypi.org/project/backports.functools-lru-cache/\r\n\r\nThank you to read."
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/560",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/560/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/560/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/560/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/pull/560",
        "id": 537401003,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzUyNzYzOTM0",
        "number": 560,
        "title": "Update estimator.py",
        "user": {
            "login": "varadkulk",
            "id": 40574811,
            "node_id": "MDQ6VXNlcjQwNTc0ODEx",
            "avatar_url": "https://avatars2.githubusercontent.com/u/40574811?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/varadkulk",
            "html_url": "https://github.com/varadkulk",
            "followers_url": "https://api.github.com/users/varadkulk/followers",
            "following_url": "https://api.github.com/users/varadkulk/following{/other_user}",
            "gists_url": "https://api.github.com/users/varadkulk/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/varadkulk/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/varadkulk/subscriptions",
            "organizations_url": "https://api.github.com/users/varadkulk/orgs",
            "repos_url": "https://api.github.com/users/varadkulk/repos",
            "events_url": "https://api.github.com/users/varadkulk/events{/privacy}",
            "received_events_url": "https://api.github.com/users/varadkulk/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-13T07:54:45Z",
        "updated_at": "2019-12-13T07:54:45Z",
        "closed_at": null,
        "author_association": "NONE",
        "pull_request": {
            "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/pulls/560",
            "html_url": "https://github.com/ildoonet/tf-pose-estimation/pull/560",
            "diff_url": "https://github.com/ildoonet/tf-pose-estimation/pull/560.diff",
            "patch_url": "https://github.com/ildoonet/tf-pose-estimation/pull/560.patch"
        },
        "body": "Solves #559"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/559",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/559/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/559/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/559/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/559",
        "id": 536211167,
        "node_id": "MDU6SXNzdWU1MzYyMTExNjc=",
        "number": 559,
        "title": " No module named 'tensorflow.contrib.tensorrt'",
        "user": {
            "login": "chde222",
            "id": 45227620,
            "node_id": "MDQ6VXNlcjQ1MjI3NjIw",
            "avatar_url": "https://avatars2.githubusercontent.com/u/45227620?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/chde222",
            "html_url": "https://github.com/chde222",
            "followers_url": "https://api.github.com/users/chde222/followers",
            "following_url": "https://api.github.com/users/chde222/following{/other_user}",
            "gists_url": "https://api.github.com/users/chde222/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/chde222/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/chde222/subscriptions",
            "organizations_url": "https://api.github.com/users/chde222/orgs",
            "repos_url": "https://api.github.com/users/chde222/repos",
            "events_url": "https://api.github.com/users/chde222/events{/privacy}",
            "received_events_url": "https://api.github.com/users/chde222/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 12,
        "created_at": "2019-12-11T08:18:16Z",
        "updated_at": "2019-12-16T12:36:48Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\u6211\u6309\u7167\u5b89\u88c5\u6b65\u9aa4\u5b89\u88c5\u5b8c\u540e\uff0c\u62a5\u8fd9\u4e2a\u9519\u8bef\u3002\u8bf7\u95ee\u8fd9\u4e2a\u5e94\u8be5\u600e\u4e48\u529e \u662f\u9700\u8981\u5355\u72ec\u5b89\u88c5\u5417 \u6211\u662fwindows\u7248\u672c"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/558",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/558/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/558/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/558/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/558",
        "id": 533336828,
        "node_id": "MDU6SXNzdWU1MzMzMzY4Mjg=",
        "number": 558,
        "title": "Pre/Post processing for mobile",
        "user": {
            "login": "iabdrashitov",
            "id": 19252309,
            "node_id": "MDQ6VXNlcjE5MjUyMzA5",
            "avatar_url": "https://avatars1.githubusercontent.com/u/19252309?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/iabdrashitov",
            "html_url": "https://github.com/iabdrashitov",
            "followers_url": "https://api.github.com/users/iabdrashitov/followers",
            "following_url": "https://api.github.com/users/iabdrashitov/following{/other_user}",
            "gists_url": "https://api.github.com/users/iabdrashitov/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/iabdrashitov/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/iabdrashitov/subscriptions",
            "organizations_url": "https://api.github.com/users/iabdrashitov/orgs",
            "repos_url": "https://api.github.com/users/iabdrashitov/repos",
            "events_url": "https://api.github.com/users/iabdrashitov/events{/privacy}",
            "received_events_url": "https://api.github.com/users/iabdrashitov/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-05T13:00:21Z",
        "updated_at": "2019-12-05T13:00:21Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Hi guys, \r\nDoes anyone have or seen somewhere java implementation of pre and post processing of the model`s input/output for android? This model works well as desktop python application was wondering if it will work the same way on android\r\n\r\nThanks"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/555",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/555/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/555/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/555/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/555",
        "id": 531822549,
        "node_id": "MDU6SXNzdWU1MzE4MjI1NDk=",
        "number": 555,
        "title": "openpose And tf-pose-estimation",
        "user": {
            "login": "AndroidUnityGit",
            "id": 50740901,
            "node_id": "MDQ6VXNlcjUwNzQwOTAx",
            "avatar_url": "https://avatars2.githubusercontent.com/u/50740901?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AndroidUnityGit",
            "html_url": "https://github.com/AndroidUnityGit",
            "followers_url": "https://api.github.com/users/AndroidUnityGit/followers",
            "following_url": "https://api.github.com/users/AndroidUnityGit/following{/other_user}",
            "gists_url": "https://api.github.com/users/AndroidUnityGit/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/AndroidUnityGit/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AndroidUnityGit/subscriptions",
            "organizations_url": "https://api.github.com/users/AndroidUnityGit/orgs",
            "repos_url": "https://api.github.com/users/AndroidUnityGit/repos",
            "events_url": "https://api.github.com/users/AndroidUnityGit/events{/privacy}",
            "received_events_url": "https://api.github.com/users/AndroidUnityGit/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-03T08:51:18Z",
        "updated_at": "2019-12-03T08:51:18Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Can you tell me the difference between the openpose and tf-pose-estimation?"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/554",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/554/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/554/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/554/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/554",
        "id": 530525500,
        "node_id": "MDU6SXNzdWU1MzA1MjU1MDA=",
        "number": 554,
        "title": "Please help. \"No module named '_pafprocess'\"",
        "user": {
            "login": "GenoXxx",
            "id": 43890413,
            "node_id": "MDQ6VXNlcjQzODkwNDEz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/43890413?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/GenoXxx",
            "html_url": "https://github.com/GenoXxx",
            "followers_url": "https://api.github.com/users/GenoXxx/followers",
            "following_url": "https://api.github.com/users/GenoXxx/following{/other_user}",
            "gists_url": "https://api.github.com/users/GenoXxx/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/GenoXxx/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/GenoXxx/subscriptions",
            "organizations_url": "https://api.github.com/users/GenoXxx/orgs",
            "repos_url": "https://api.github.com/users/GenoXxx/repos",
            "events_url": "https://api.github.com/users/GenoXxx/events{/privacy}",
            "received_events_url": "https://api.github.com/users/GenoXxx/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 12,
        "created_at": "2019-11-30T03:12:22Z",
        "updated_at": "2020-01-22T10:34:07Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Forgive me for being so under experienced with this, but nearly all day i've been trying to fix this issue.  I recently stumbled upon an author who made the mmdmatic program and I really wanted to try it. I believe i did everything I saw him do in the vid. The only error I'm getting is:\r\n\"No module named '_pafprocess'\"\r\n\"you need to build c++ library for pafprocess.\"\r\n\r\nI tried everything i could  do on my own including attempts to learn c++ coding. I even apparently came upon the same issue others had here, but as someone who knows next to nothing of this sort of thing, I don't understand the steps to fixing it at all. \r\n\r\nCould someone please help me understand and explain what I should do?\r\n"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/553",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/553/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/553/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/553/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/pull/553",
        "id": 530518295,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzQ3MTgyMzQx",
        "number": 553,
        "title": "fixes the typo in README.md (etc \u2192 etcs)",
        "user": {
            "login": "makc",
            "id": 242577,
            "node_id": "MDQ6VXNlcjI0MjU3Nw==",
            "avatar_url": "https://avatars0.githubusercontent.com/u/242577?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/makc",
            "html_url": "https://github.com/makc",
            "followers_url": "https://api.github.com/users/makc/followers",
            "following_url": "https://api.github.com/users/makc/following{/other_user}",
            "gists_url": "https://api.github.com/users/makc/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/makc/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/makc/subscriptions",
            "organizations_url": "https://api.github.com/users/makc/orgs",
            "repos_url": "https://api.github.com/users/makc/repos",
            "events_url": "https://api.github.com/users/makc/events{/privacy}",
            "received_events_url": "https://api.github.com/users/makc/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-30T01:26:54Z",
        "updated_at": "2019-11-30T01:26:54Z",
        "closed_at": null,
        "author_association": "NONE",
        "pull_request": {
            "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/pulls/553",
            "html_url": "https://github.com/ildoonet/tf-pose-estimation/pull/553",
            "diff_url": "https://github.com/ildoonet/tf-pose-estimation/pull/553.diff",
            "patch_url": "https://github.com/ildoonet/tf-pose-estimation/pull/553.patch"
        },
        "body": ""
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/552",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/552/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/552/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/552/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/552",
        "id": 530224529,
        "node_id": "MDU6SXNzdWU1MzAyMjQ1Mjk=",
        "number": 552,
        "title": "TypeError: inference() got an unexpected keyword argument 'scales'",
        "user": {
            "login": "DropYearning",
            "id": 46500169,
            "node_id": "MDQ6VXNlcjQ2NTAwMTY5",
            "avatar_url": "https://avatars0.githubusercontent.com/u/46500169?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/DropYearning",
            "html_url": "https://github.com/DropYearning",
            "followers_url": "https://api.github.com/users/DropYearning/followers",
            "following_url": "https://api.github.com/users/DropYearning/following{/other_user}",
            "gists_url": "https://api.github.com/users/DropYearning/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/DropYearning/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/DropYearning/subscriptions",
            "organizations_url": "https://api.github.com/users/DropYearning/orgs",
            "repos_url": "https://api.github.com/users/DropYearning/repos",
            "events_url": "https://api.github.com/users/DropYearning/events{/privacy}",
            "received_events_url": "https://api.github.com/users/DropYearning/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-29T08:48:42Z",
        "updated_at": "2019-11-29T08:48:42Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "when I run `run_directory.py` in my computer, it shows `TypeError: inference() got an unexpected keyword argument 'scales'`. \r\nI don't want results in [0,1] , I need results which are coordinates of x and y in their source images.\r\nHow can i do it ?"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/551",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/551/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/551/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/551/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/551",
        "id": 528241963,
        "node_id": "MDU6SXNzdWU1MjgyNDE5NjM=",
        "number": 551,
        "title": "pafprocess_wrap.cpp(5672): error C3861: 'rb_require': identifier not found",
        "user": {
            "login": "rashiAg122",
            "id": 57704078,
            "node_id": "MDQ6VXNlcjU3NzA0MDc4",
            "avatar_url": "https://avatars1.githubusercontent.com/u/57704078?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rashiAg122",
            "html_url": "https://github.com/rashiAg122",
            "followers_url": "https://api.github.com/users/rashiAg122/followers",
            "following_url": "https://api.github.com/users/rashiAg122/following{/other_user}",
            "gists_url": "https://api.github.com/users/rashiAg122/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rashiAg122/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rashiAg122/subscriptions",
            "organizations_url": "https://api.github.com/users/rashiAg122/orgs",
            "repos_url": "https://api.github.com/users/rashiAg122/repos",
            "events_url": "https://api.github.com/users/rashiAg122/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rashiAg122/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-25T17:50:06Z",
        "updated_at": "2019-11-25T17:50:06Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I used \"swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace\" command and got the following error:\r\npafprocess_wrap.cpp(5672): error C3861: 'rb_require': identifier not found\r\nerror: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.23.28105\\\\bin\\\\HostX86\\\\x86\\\\cl.exe' failed with exit status 2"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/550",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/550/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/550/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/550/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/550",
        "id": 527920206,
        "node_id": "MDU6SXNzdWU1Mjc5MjAyMDY=",
        "number": 550,
        "title": "use trt graph question",
        "user": {
            "login": "huwade",
            "id": 8497968,
            "node_id": "MDQ6VXNlcjg0OTc5Njg=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/8497968?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/huwade",
            "html_url": "https://github.com/huwade",
            "followers_url": "https://api.github.com/users/huwade/followers",
            "following_url": "https://api.github.com/users/huwade/following{/other_user}",
            "gists_url": "https://api.github.com/users/huwade/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/huwade/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/huwade/subscriptions",
            "organizations_url": "https://api.github.com/users/huwade/orgs",
            "repos_url": "https://api.github.com/users/huwade/repos",
            "events_url": "https://api.github.com/users/huwade/events{/privacy}",
            "received_events_url": "https://api.github.com/users/huwade/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-25T08:12:32Z",
        "updated_at": "2019-11-25T08:12:32Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "In estimator.py, line 330 to 332\r\n\r\nIf I create TensorRT inference graph, then I should import the TensorRT graph into a new graph and run. So I don't understand why you get the default graph first and then import the graph.\r\n"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/549",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/549/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/549/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/549/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/549",
        "id": 527653389,
        "node_id": "MDU6SXNzdWU1Mjc2NTMzODk=",
        "number": 549,
        "title": "Having trouble with the requirements.txt part ",
        "user": {
            "login": "newStudent1050",
            "id": 58126875,
            "node_id": "MDQ6VXNlcjU4MTI2ODc1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/58126875?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/newStudent1050",
            "html_url": "https://github.com/newStudent1050",
            "followers_url": "https://api.github.com/users/newStudent1050/followers",
            "following_url": "https://api.github.com/users/newStudent1050/following{/other_user}",
            "gists_url": "https://api.github.com/users/newStudent1050/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/newStudent1050/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/newStudent1050/subscriptions",
            "organizations_url": "https://api.github.com/users/newStudent1050/orgs",
            "repos_url": "https://api.github.com/users/newStudent1050/repos",
            "events_url": "https://api.github.com/users/newStudent1050/events{/privacy}",
            "received_events_url": "https://api.github.com/users/newStudent1050/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 4,
        "created_at": "2019-11-24T05:43:38Z",
        "updated_at": "2019-12-22T07:33:20Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I've seen a few of the other posts about this not working and despite troubleshooting I still haven't been able to get it to work.\r\n\r\nThis is the error message I am getting :\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/548",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/548/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/548/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/548/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/548",
        "id": 526401377,
        "node_id": "MDU6SXNzdWU1MjY0MDEzNzc=",
        "number": 548,
        "title": "openpose oks on ai challenge dataset??",
        "user": {
            "login": "henbucuoshanghai",
            "id": 37647094,
            "node_id": "MDQ6VXNlcjM3NjQ3MDk0",
            "avatar_url": "https://avatars1.githubusercontent.com/u/37647094?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/henbucuoshanghai",
            "html_url": "https://github.com/henbucuoshanghai",
            "followers_url": "https://api.github.com/users/henbucuoshanghai/followers",
            "following_url": "https://api.github.com/users/henbucuoshanghai/following{/other_user}",
            "gists_url": "https://api.github.com/users/henbucuoshanghai/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/henbucuoshanghai/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/henbucuoshanghai/subscriptions",
            "organizations_url": "https://api.github.com/users/henbucuoshanghai/orgs",
            "repos_url": "https://api.github.com/users/henbucuoshanghai/repos",
            "events_url": "https://api.github.com/users/henbucuoshanghai/events{/privacy}",
            "received_events_url": "https://api.github.com/users/henbucuoshanghai/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-11-21T06:55:20Z",
        "updated_at": "2019-11-21T06:56:01Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "the performance of openpose on  ai challenge dataset??"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/546",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/546/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/546/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/546/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/546",
        "id": 523971904,
        "node_id": "MDU6SXNzdWU1MjM5NzE5MDQ=",
        "number": 546,
        "title": "BrokenPipeError: [Errno 32] Broken pipe",
        "user": {
            "login": "khan958",
            "id": 47415910,
            "node_id": "MDQ6VXNlcjQ3NDE1OTEw",
            "avatar_url": "https://avatars3.githubusercontent.com/u/47415910?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/khan958",
            "html_url": "https://github.com/khan958",
            "followers_url": "https://api.github.com/users/khan958/followers",
            "following_url": "https://api.github.com/users/khan958/following{/other_user}",
            "gists_url": "https://api.github.com/users/khan958/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/khan958/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/khan958/subscriptions",
            "organizations_url": "https://api.github.com/users/khan958/orgs",
            "repos_url": "https://api.github.com/users/khan958/repos",
            "events_url": "https://api.github.com/users/khan958/events{/privacy}",
            "received_events_url": "https://api.github.com/users/khan958/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-17T11:28:33Z",
        "updated_at": "2019-11-17T11:28:33Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "When i run the train.py command it shows me this error.\r\n\r\nForkingPickler(file, protocol).dump(obj)\r\n\r\nBrokenPipeError: [Errno 32] Broken pipe"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/544",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/544/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/544/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/544/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/544",
        "id": 523412483,
        "node_id": "MDU6SXNzdWU1MjM0MTI0ODM=",
        "number": 544,
        "title": "ModuleNotFoundError: No module named 'tf_pose'",
        "user": {
            "login": "khan958",
            "id": 47415910,
            "node_id": "MDQ6VXNlcjQ3NDE1OTEw",
            "avatar_url": "https://avatars3.githubusercontent.com/u/47415910?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/khan958",
            "html_url": "https://github.com/khan958",
            "followers_url": "https://api.github.com/users/khan958/followers",
            "following_url": "https://api.github.com/users/khan958/following{/other_user}",
            "gists_url": "https://api.github.com/users/khan958/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/khan958/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/khan958/subscriptions",
            "organizations_url": "https://api.github.com/users/khan958/orgs",
            "repos_url": "https://api.github.com/users/khan958/repos",
            "events_url": "https://api.github.com/users/khan958/events{/privacy}",
            "received_events_url": "https://api.github.com/users/khan958/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-15T11:19:01Z",
        "updated_at": "2019-11-15T11:19:01Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "When i run train.py it shows me this error? Any one can solve this ?\r\n\r\nFile \"train.py\", line 14, in <module>\r\n    from pose_dataset import get_dataflow_batch, DataFlowToQueue, CocoPose\r\n  File \"C:\\Users\\IrfanKhan\\tf-pose-estimation-master\\tf_pose\\pose_dataset.py\", line 31, in <module>\r\n    from pose_augment import pose_flip, pose_rotation, pose_to_img, pose_crop_random, \\\r\n  File \"C:\\Users\\IrfanKhan\\tf-pose-estimation-master\\tf_pose\\pose_augment.py\", line 8, in <module>\r\n    from tf_pose.common import CocoPart\r\nModuleNotFoundError: No module named 'tf_pose'"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/543",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/543/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/543/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/543/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/543",
        "id": 523313368,
        "node_id": "MDU6SXNzdWU1MjMzMTMzNjg=",
        "number": 543,
        "title": "TensorRT verison",
        "user": {
            "login": "Luke0426",
            "id": 45222675,
            "node_id": "MDQ6VXNlcjQ1MjIyNjc1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/45222675?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Luke0426",
            "html_url": "https://github.com/Luke0426",
            "followers_url": "https://api.github.com/users/Luke0426/followers",
            "following_url": "https://api.github.com/users/Luke0426/following{/other_user}",
            "gists_url": "https://api.github.com/users/Luke0426/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Luke0426/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Luke0426/subscriptions",
            "organizations_url": "https://api.github.com/users/Luke0426/orgs",
            "repos_url": "https://api.github.com/users/Luke0426/repos",
            "events_url": "https://api.github.com/users/Luke0426/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Luke0426/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-15T07:57:20Z",
        "updated_at": "2019-11-15T07:57:20Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "When i run the script run_webcam.py with mobilenet_v2 and enabled tensorRT,i get the warning:\r\nWARNING:tensorflow:TensorRT mismatch. Compiled against version 3.0.4, but loaded 4.0.1. Things may not work.\r\nAnd those errors:\r\nTfPoseEstimator/MobilenetV2/Conv/my_trt_op_13 Constructing a new engine with batch size 1\r\nEngine creation for batch size 1 failed Unimplemented: Not supported constant type, at MobilenetV2/Conv/BatchNorm/Const\r\nEngine retrieval for batch size 1 failed Running native segment\r\nFinally the result was:\r\ntensorflow.python.framework.errors_impl.InternalError: Engine creation failed!\r\nMy tensorflow version is 1.10-gpu,how could i solve this problem?"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/542",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/542/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/542/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/542/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/542",
        "id": 522649418,
        "node_id": "MDU6SXNzdWU1MjI2NDk0MTg=",
        "number": 542,
        "title": "Permission denied",
        "user": {
            "login": "naveen-770",
            "id": 39587594,
            "node_id": "MDQ6VXNlcjM5NTg3NTk0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/39587594?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/naveen-770",
            "html_url": "https://github.com/naveen-770",
            "followers_url": "https://api.github.com/users/naveen-770/followers",
            "following_url": "https://api.github.com/users/naveen-770/following{/other_user}",
            "gists_url": "https://api.github.com/users/naveen-770/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/naveen-770/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/naveen-770/subscriptions",
            "organizations_url": "https://api.github.com/users/naveen-770/orgs",
            "repos_url": "https://api.github.com/users/naveen-770/repos",
            "events_url": "https://api.github.com/users/naveen-770/events{/privacy}",
            "received_events_url": "https://api.github.com/users/naveen-770/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-14T06:17:02Z",
        "updated_at": "2019-11-14T06:17:02Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I gave the command to run the model on a video and i am getting permission denied.\r\nPermissionError: [Errno 13] Permission denied: 'C:\\\\Users\\\\Naveen\\\\.matplotlib\\\\fontlist-v310.json.matplotlib-lock'\r\n![err](https://user-images.githubusercontent.com/39587594/68831476-74c32180-06d4-11ea-9d5f-1539645006d1.PNG)\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/541",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/541/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/541/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/541/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/541",
        "id": 521452757,
        "node_id": "MDU6SXNzdWU1MjE0NTI3NTc=",
        "number": 541,
        "title": "Issue regarding missing key points",
        "user": {
            "login": "arnabdeypolimi",
            "id": 32412133,
            "node_id": "MDQ6VXNlcjMyNDEyMTMz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/32412133?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/arnabdeypolimi",
            "html_url": "https://github.com/arnabdeypolimi",
            "followers_url": "https://api.github.com/users/arnabdeypolimi/followers",
            "following_url": "https://api.github.com/users/arnabdeypolimi/following{/other_user}",
            "gists_url": "https://api.github.com/users/arnabdeypolimi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/arnabdeypolimi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/arnabdeypolimi/subscriptions",
            "organizations_url": "https://api.github.com/users/arnabdeypolimi/orgs",
            "repos_url": "https://api.github.com/users/arnabdeypolimi/repos",
            "events_url": "https://api.github.com/users/arnabdeypolimi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/arnabdeypolimi/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-12T10:11:59Z",
        "updated_at": "2019-11-12T10:11:59Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I would like to have all the key points values all the time. In my experiments I have seen that sometimes it missing some key points values. But my implementaion need all the keypoints everytimes even if the accuracy is really bad for those key points. Is there a way to solve this issue."
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/540",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/540/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/540/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/540/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/540",
        "id": 520411020,
        "node_id": "MDU6SXNzdWU1MjA0MTEwMjA=",
        "number": 540,
        "title": " ForkingPickler(file, protocol).dump(obj)  BrokenPipeError: [Errno 32] Broken pipe",
        "user": {
            "login": "khan958",
            "id": 47415910,
            "node_id": "MDQ6VXNlcjQ3NDE1OTEw",
            "avatar_url": "https://avatars3.githubusercontent.com/u/47415910?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/khan958",
            "html_url": "https://github.com/khan958",
            "followers_url": "https://api.github.com/users/khan958/followers",
            "following_url": "https://api.github.com/users/khan958/following{/other_user}",
            "gists_url": "https://api.github.com/users/khan958/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/khan958/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/khan958/subscriptions",
            "organizations_url": "https://api.github.com/users/khan958/orgs",
            "repos_url": "https://api.github.com/users/khan958/repos",
            "events_url": "https://api.github.com/users/khan958/events{/privacy}",
            "received_events_url": "https://api.github.com/users/khan958/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-09T12:32:28Z",
        "updated_at": "2019-11-09T12:32:28Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": ""
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/539",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/539/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/539/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/539/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/539",
        "id": 519347362,
        "node_id": "MDU6SXNzdWU1MTkzNDczNjI=",
        "number": 539,
        "title": "FileNotFoundError: [Errno 2] No such file or directory: '/data/public/rw/coco/annotations/person_keypoints_train2017.json'",
        "user": {
            "login": "khan958",
            "id": 47415910,
            "node_id": "MDQ6VXNlcjQ3NDE1OTEw",
            "avatar_url": "https://avatars3.githubusercontent.com/u/47415910?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/khan958",
            "html_url": "https://github.com/khan958",
            "followers_url": "https://api.github.com/users/khan958/followers",
            "following_url": "https://api.github.com/users/khan958/following{/other_user}",
            "gists_url": "https://api.github.com/users/khan958/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/khan958/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/khan958/subscriptions",
            "organizations_url": "https://api.github.com/users/khan958/orgs",
            "repos_url": "https://api.github.com/users/khan958/repos",
            "events_url": "https://api.github.com/users/khan958/events{/privacy}",
            "received_events_url": "https://api.github.com/users/khan958/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-07T15:44:12Z",
        "updated_at": "2019-11-07T15:44:12Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\r\n  File \"C:\\Users\\Jackson\\Anaconda3\\envs\\tf-pose-estimation\\lib\\site-packages\\pycocotools\\coco.py\", line 84, in __init__\r\n    dataset = json.load(open(annotation_file, ))\r\n\r\nFileNotFoundError: [Errno 2] No such file or directory: '/data/public/rw/coco/annotations/person_keypoints_train2017.json"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/538",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/538/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/538/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/538/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/538",
        "id": 518883437,
        "node_id": "MDU6SXNzdWU1MTg4ODM0Mzc=",
        "number": 538,
        "title": "Slow on Jetson Tx2",
        "user": {
            "login": "danigusm",
            "id": 56343690,
            "node_id": "MDQ6VXNlcjU2MzQzNjkw",
            "avatar_url": "https://avatars1.githubusercontent.com/u/56343690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/danigusm",
            "html_url": "https://github.com/danigusm",
            "followers_url": "https://api.github.com/users/danigusm/followers",
            "following_url": "https://api.github.com/users/danigusm/following{/other_user}",
            "gists_url": "https://api.github.com/users/danigusm/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/danigusm/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/danigusm/subscriptions",
            "organizations_url": "https://api.github.com/users/danigusm/orgs",
            "repos_url": "https://api.github.com/users/danigusm/repos",
            "events_url": "https://api.github.com/users/danigusm/events{/privacy}",
            "received_events_url": "https://api.github.com/users/danigusm/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-11-06T22:29:41Z",
        "updated_at": "2019-11-09T04:12:39Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Running on Jetson Tx2 with mobilenet-thin is very slow compared to the expectations, I get 5fps but on the repo it seems to run at 10fps.\r\nEven more when I launch run_webcam I takes a while to start and a warning message is displayed:\r\n`Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.33GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.`\r\nAnyone can help me?\r\n"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/537",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/537/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/537/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/537/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/537",
        "id": 516871053,
        "node_id": "MDU6SXNzdWU1MTY4NzEwNTM=",
        "number": 537,
        "title": "ModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'",
        "user": {
            "login": "khan958",
            "id": 47415910,
            "node_id": "MDQ6VXNlcjQ3NDE1OTEw",
            "avatar_url": "https://avatars3.githubusercontent.com/u/47415910?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/khan958",
            "html_url": "https://github.com/khan958",
            "followers_url": "https://api.github.com/users/khan958/followers",
            "following_url": "https://api.github.com/users/khan958/following{/other_user}",
            "gists_url": "https://api.github.com/users/khan958/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/khan958/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/khan958/subscriptions",
            "organizations_url": "https://api.github.com/users/khan958/orgs",
            "repos_url": "https://api.github.com/users/khan958/repos",
            "events_url": "https://api.github.com/users/khan958/events{/privacy}",
            "received_events_url": "https://api.github.com/users/khan958/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-11-03T18:43:47Z",
        "updated_at": "2019-11-27T13:14:39Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\r\n  File \"C:\\Users\\Jayden\\tf-pose-estimation-master\\tf_pose\\estimator.py\", line 14, in <module>\r\n    import tensorflow.contrib.tensorrt as trt\r\n\r\nModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'"
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/536",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/536/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/536/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/536/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/536",
        "id": 516045893,
        "node_id": "MDU6SXNzdWU1MTYwNDU4OTM=",
        "number": 536,
        "title": "issue with tensorflow 2.0",
        "user": {
            "login": "arnabdeypolimi",
            "id": 32412133,
            "node_id": "MDQ6VXNlcjMyNDEyMTMz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/32412133?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/arnabdeypolimi",
            "html_url": "https://github.com/arnabdeypolimi",
            "followers_url": "https://api.github.com/users/arnabdeypolimi/followers",
            "following_url": "https://api.github.com/users/arnabdeypolimi/following{/other_user}",
            "gists_url": "https://api.github.com/users/arnabdeypolimi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/arnabdeypolimi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/arnabdeypolimi/subscriptions",
            "organizations_url": "https://api.github.com/users/arnabdeypolimi/orgs",
            "repos_url": "https://api.github.com/users/arnabdeypolimi/repos",
            "events_url": "https://api.github.com/users/arnabdeypolimi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/arnabdeypolimi/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-11-01T10:57:56Z",
        "updated_at": "2019-11-12T10:04:32Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "ModuleNotFoundError: No module named 'tensorflow.contrib'\r\ncan you fix this so that it can work with tensorflow 2.0 "
    },
    {
        "url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/535",
        "repository_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation",
        "labels_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/535/labels{/name}",
        "comments_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/535/comments",
        "events_url": "https://api.github.com/repos/ildoonet/tf-pose-estimation/issues/535/events",
        "html_url": "https://github.com/ildoonet/tf-pose-estimation/issues/535",
        "id": 514857610,
        "node_id": "MDU6SXNzdWU1MTQ4NTc2MTA=",
        "number": 535,
        "title": "AttributeError: module 'tensorflow' has no attribute 'nn'",
        "user": {
            "login": "khan958",
            "id": 47415910,
            "node_id": "MDQ6VXNlcjQ3NDE1OTEw",
            "avatar_url": "https://avatars3.githubusercontent.com/u/47415910?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/khan958",
            "html_url": "https://github.com/khan958",
            "followers_url": "https://api.github.com/users/khan958/followers",
            "following_url": "https://api.github.com/users/khan958/following{/other_user}",
            "gists_url": "https://api.github.com/users/khan958/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/khan958/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/khan958/subscriptions",
            "organizations_url": "https://api.github.com/users/khan958/orgs",
            "repos_url": "https://api.github.com/users/khan958/repos",
            "events_url": "https://api.github.com/users/khan958/events{/privacy}",
            "received_events_url": "https://api.github.com/users/khan958/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-10-30T17:37:36Z",
        "updated_at": "2020-01-10T07:39:41Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "When i am trying to run_webcam.py,    it show me this error?    \r\n\r\nactivation_fn = tf.nn.relu\r\n\r\nAttributeError: module 'tensorflow' has no attribute 'nn'"
    }
]