[
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/31",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/31/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/31/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/31/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/31",
        "id": 560931862,
        "node_id": "MDU6SXNzdWU1NjA5MzE4NjI=",
        "number": 31,
        "title": "Issue with the load_model function of the cortoogan folder",
        "user": {
            "login": "Angkirat",
            "id": 18494442,
            "node_id": "MDQ6VXNlcjE4NDk0NDQy",
            "avatar_url": "https://avatars0.githubusercontent.com/u/18494442?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Angkirat",
            "html_url": "https://github.com/Angkirat",
            "followers_url": "https://api.github.com/users/Angkirat/followers",
            "following_url": "https://api.github.com/users/Angkirat/following{/other_user}",
            "gists_url": "https://api.github.com/users/Angkirat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Angkirat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Angkirat/subscriptions",
            "organizations_url": "https://api.github.com/users/Angkirat/orgs",
            "repos_url": "https://api.github.com/users/Angkirat/repos",
            "events_url": "https://api.github.com/users/Angkirat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Angkirat/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-06T10:52:22Z",
        "updated_at": "2020-02-06T11:08:13Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I am facing issue while executing the code as below:\r\n\r\ncould you please help resolve this\r\n\r\n```020-02-06 15:50:58.659955: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found\r\n2020-02-06 15:50:58.660293: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\r\nUsing TensorFlow backend.\r\n2020-02-06 15:51:10.433049: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found\r\n2020-02-06 15:51:10.433434: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)\r\n2020-02-06 15:51:10.447289: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DDC2-D-6SGR9B2\r\n2020-02-06 15:51:10.448351: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DDC2-D-6SGR9B2\r\n2020-02-06 15:51:10.448868: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraceback (most recent call last):\r\n  File \"~/OneDrive/PythonCode/AIR_Open_funEvents/cartoonization/cartoongan.py\", line 149, in <module>\r\n    g = load_model(\"hayao\")\r\n  File \"~/OneDrive/PythonCode/AIR_Open_funEvents/cartoonization/cartoongan.py\", line 82, in load_model\r\n    y = instance_norm_layer(style, \"in01_1\")(y)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 75, in symbolic_fn_wrapper\r\n    return func(*args, **kwargs)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 463, in __call__\r\n    self.build(unpack_singleton(input_shapes))\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\keras_contrib-2.0.8-py3.6.egg\\keras_contrib\\layers\\normalization\\instancenormalization.py\", line 95, in build\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 282, in add_weight\r\n    constraint=constraint)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 620, in variable\r\n    value, dtype=dtype, name=name, constraint=constraint)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\keras\\backend.py\", line 814, in variable\r\n    constraint=constraint)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\ops\\variables.py\", line 260, in __call__\r\n    return cls._variable_v2_call(*args, **kwargs)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\ops\\variables.py\", line 254, in _variable_v2_call\r\n    shape=shape)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\ops\\variables.py\", line 235, in <lambda>\r\n    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\ops\\variable_scope.py\", line 2645, in default_variable_creator_v2\r\n    shape=shape)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\ops\\variables.py\", line 262, in __call__\r\n    return super(VariableMetaclass, cls).__call__(*args, **kwargs)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\ops\\resource_variable_ops.py\", line 1411, in __init__\r\n    distribute_strategy=distribute_strategy)\r\n  File \"~\\AppData\\Local\\Continuum\\anaconda3\\envs\\MyEnv\\lib\\site-packages\\tensorflow_core\\python\\ops\\resource_variable_ops.py\", line 1494, in _init_from_args\r\n    raise ValueError(\"Tensor-typed variable initializers must either be \"\r\nValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.```\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/29",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/29/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/29/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/29/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/29",
        "id": 535694583,
        "node_id": "MDU6SXNzdWU1MzU2OTQ1ODM=",
        "number": 29,
        "title": "OOM Resource Exhausted after one epoch",
        "user": {
            "login": "giuliacern",
            "id": 49780486,
            "node_id": "MDQ6VXNlcjQ5NzgwNDg2",
            "avatar_url": "https://avatars1.githubusercontent.com/u/49780486?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/giuliacern",
            "html_url": "https://github.com/giuliacern",
            "followers_url": "https://api.github.com/users/giuliacern/followers",
            "following_url": "https://api.github.com/users/giuliacern/following{/other_user}",
            "gists_url": "https://api.github.com/users/giuliacern/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/giuliacern/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/giuliacern/subscriptions",
            "organizations_url": "https://api.github.com/users/giuliacern/orgs",
            "repos_url": "https://api.github.com/users/giuliacern/repos",
            "events_url": "https://api.github.com/users/giuliacern/events{/privacy}",
            "received_events_url": "https://api.github.com/users/giuliacern/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 7,
        "created_at": "2019-12-10T12:21:33Z",
        "updated_at": "2020-01-11T02:53:03Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Hi! I trained your model with Google Colab, and after an entire epoch of trained a get this error\r\n\r\n`Traceback (most recent call last):\r\n  File \"train.py\", line 707, in <module>\r\n    main(**kwargs)\r\n  File \"train.py\", line 645, in main\r\n    t.train_gan()\r\n  File \"train.py\", line 624, in train_gan\r\n    (generator(val_real_batch, training=False) + 1) * 127.5, tf.uint8)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 660, in __call__\r\n    outputs = self.call(inputs, *args, **kwargs)\r\n  File \"/content/drive/My Drive/CartoonGan-tensorflow/generator.py\", line 68, in call\r\n    x = self.flat_conv1(x, training=training)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 660, in __call__\r\n    outputs = self.call(inputs, *args, **kwargs)\r\n  File \"/content/drive/My Drive/CartoonGan-tensorflow/layers.py\", line 73, in call\r\n    return self.model(x, training=training)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 660, in __call__\r\n    outputs = self.call(inputs, *args, **kwargs)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py\", line 256, in call\r\n    outputs = layer(inputs, **kwargs)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 660, in __call__\r\n    outputs = self.call(inputs, *args, **kwargs)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py\", line 196, in call\r\n    outputs = self._convolution_op(inputs, self.kernel)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 1078, in __call__\r\n    return self.conv_op(inp, filter)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 634, in __call__\r\n    return self.call(inp, filter)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 233, in __call__\r\n    name=self.name)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 1951, in conv2d\r\n    name=name)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py\", line 1031, in conv2d\r\n    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py\", line 1130, in conv2d_eager_fallback\r\n    ctx=_ctx, name=name)\r\n  File \"/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/eager/execute.py\", line 66, in quick_execute\r\n    six.raise_from(core._status_to_exception(e.code, message), None)\r\n  File \"<string>\", line 3, in raise_from\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1117,256,256,96] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Conv2D]`\r\n\r\nI partially solved this issue by simply saving the checkpoints and weights before the end of the epoch and then retraining again, until the crash. \r\nInitially I thought that the model is too big, so I set up the batch size to 1, but still the problem persist. \r\nI think that there is a memory leak somewhere. Maybe at the end of the epoch you create new tensors or a copy of the entire model. I haven't checked yet but I'm going to update if I find something."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/28",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/28/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/28/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/28/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/28",
        "id": 528757234,
        "node_id": "MDU6SXNzdWU1Mjg3NTcyMzQ=",
        "number": 28,
        "title": "About load pretrained model",
        "user": {
            "login": "klyuhang9",
            "id": 39409233,
            "node_id": "MDQ6VXNlcjM5NDA5MjMz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/39409233?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/klyuhang9",
            "html_url": "https://github.com/klyuhang9",
            "followers_url": "https://api.github.com/users/klyuhang9/followers",
            "following_url": "https://api.github.com/users/klyuhang9/following{/other_user}",
            "gists_url": "https://api.github.com/users/klyuhang9/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/klyuhang9/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/klyuhang9/subscriptions",
            "organizations_url": "https://api.github.com/users/klyuhang9/orgs",
            "repos_url": "https://api.github.com/users/klyuhang9/repos",
            "events_url": "https://api.github.com/users/klyuhang9/events{/privacy}",
            "received_events_url": "https://api.github.com/users/klyuhang9/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-11-26T14:21:10Z",
        "updated_at": "2019-11-26T14:35:33Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Hi, I tryed to use load_model() function in \"cartoongan.py\", combined with\" ReflectionPadding2D\u3001conv_layer\u3001 instance_norm_layer\uff0c decon_layers\" 4 layers function and \"pre_processing(), post_processing()\"to processing image. However, I couldn't get the satisfied result.\r\n![picture](https://user-images.githubusercontent.com/39409233/69641204-bc658800-109a-11ea-825b-e512f740176d.jpg)\r\nI don't know why, I just as the code to load pretrained model generator, and put the input in that, but the output image is not satisfied. Thanks for your help!!\r\n\r\n\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/27",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/27/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/27/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/27/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/27",
        "id": 524137620,
        "node_id": "MDU6SXNzdWU1MjQxMzc2MjA=",
        "number": 27,
        "title": "Could you please share your dataset",
        "user": {
            "login": "siju-samuel",
            "id": 15828974,
            "node_id": "MDQ6VXNlcjE1ODI4OTc0",
            "avatar_url": "https://avatars1.githubusercontent.com/u/15828974?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/siju-samuel",
            "html_url": "https://github.com/siju-samuel",
            "followers_url": "https://api.github.com/users/siju-samuel/followers",
            "following_url": "https://api.github.com/users/siju-samuel/following{/other_user}",
            "gists_url": "https://api.github.com/users/siju-samuel/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/siju-samuel/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/siju-samuel/subscriptions",
            "organizations_url": "https://api.github.com/users/siju-samuel/orgs",
            "repos_url": "https://api.github.com/users/siju-samuel/repos",
            "events_url": "https://api.github.com/users/siju-samuel/events{/privacy}",
            "received_events_url": "https://api.github.com/users/siju-samuel/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-18T05:06:19Z",
        "updated_at": "2019-11-18T05:06:19Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "HI @mnicnc404,  Thanks for the great work.\r\nI would like to train this model by myself. Could you please send me the dataset which you have used? For any one style is ok. \r\nI need both images and style dataset. Thanks for your efforts."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/26",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/26/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/26/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/26/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/26",
        "id": 516860177,
        "node_id": "MDU6SXNzdWU1MTY4NjAxNzc=",
        "number": 26,
        "title": "Full resolution images",
        "user": {
            "login": "giuliacern",
            "id": 49780486,
            "node_id": "MDQ6VXNlcjQ5NzgwNDg2",
            "avatar_url": "https://avatars1.githubusercontent.com/u/49780486?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/giuliacern",
            "html_url": "https://github.com/giuliacern",
            "followers_url": "https://api.github.com/users/giuliacern/followers",
            "following_url": "https://api.github.com/users/giuliacern/following{/other_user}",
            "gists_url": "https://api.github.com/users/giuliacern/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/giuliacern/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/giuliacern/subscriptions",
            "organizations_url": "https://api.github.com/users/giuliacern/orgs",
            "repos_url": "https://api.github.com/users/giuliacern/repos",
            "events_url": "https://api.github.com/users/giuliacern/events{/privacy}",
            "received_events_url": "https://api.github.com/users/giuliacern/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-03T17:16:26Z",
        "updated_at": "2019-11-03T17:16:26Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Hi! I've read your paper, and I want to re-train the model with my own dataset of images. How can I do if I want to train the image in full resolution (e.g. 1920x1080)? Do I have to change the architecture and add more layers? "
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/25",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/25/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/25/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/25/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/25",
        "id": 512927921,
        "node_id": "MDU6SXNzdWU1MTI5Mjc5MjE=",
        "number": 25,
        "title": "Error running inference_with_ckpt.py",
        "user": {
            "login": "idevji1",
            "id": 34132802,
            "node_id": "MDQ6VXNlcjM0MTMyODAy",
            "avatar_url": "https://avatars3.githubusercontent.com/u/34132802?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/idevji1",
            "html_url": "https://github.com/idevji1",
            "followers_url": "https://api.github.com/users/idevji1/followers",
            "following_url": "https://api.github.com/users/idevji1/following{/other_user}",
            "gists_url": "https://api.github.com/users/idevji1/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/idevji1/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/idevji1/subscriptions",
            "organizations_url": "https://api.github.com/users/idevji1/orgs",
            "repos_url": "https://api.github.com/users/idevji1/repos",
            "events_url": "https://api.github.com/users/idevji1/events{/privacy}",
            "received_events_url": "https://api.github.com/users/idevji1/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-10-27T06:41:42Z",
        "updated_at": "2020-01-31T05:43:08Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "**Following error is encountered when running inference_with_ckpt.py :**\r\n/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\r\n/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\r\n  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\r\n[2019-10-27 06:30:31] [inference] [INFO] generating image from images/cartoonize-script-demo.jpg\r\nTraceback (most recent call last):\r\n  File \"inference_with_ckpt.py\", line 52, in <module>\r\n    main(args.m_path, args.img_path, args.out_dir, args.light)\r\n  File \"inference_with_ckpt.py\", line 23, in main\r\n    g.load_weights(tf.train.latest_checkpoint(m_path))\r\n  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py\", line 1481, in load_weights\r\n    status.assert_nontrivial_match()\r\n  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py\", line 622, in assert_nontrivial_match\r\n    \"checkpointed value: %s\") % (list(unused_python_objects),))\r\nAssertionError: Nothing except the root object matched a checkpointed value. Typically this means that the checkpoint does not match the Python program. The following objects have no matching checkpointed value: [<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd01400>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd40400>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd86400>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd37208>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd4fe10>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd81c18>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd67a20>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd37828>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd28630>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd13630>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd1f438>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd81438>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd6d438>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd18240>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd01e48>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd13e48>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd57e48>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd4fc50>, <layers.ConvBlock object at 0x7f470cd6dc50>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd1fa58>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd57860>, <layers.FlatConv object at 0x7f471cfda668>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd01278>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd40278>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd67278>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd37e80>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd40080>, <layers.ResBlock object at 0x7f470cd18080>, <layers.ResBlock object at 0x7f470cd67080>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd13c88>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470ccd9a90>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd81a90>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd40a90>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd01a90>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd5e898>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd576a0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd866a0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd284a8>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd4f4a8>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd282b0>, <layers.ResBlock object at 0x7f470cd4f2b0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd480b8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470ccd90b8>, <layers.UpSampleConv object at 0x7f470cd77eb8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd770b8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd57cc0>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd28cc0>, <tensorflow.python.keras.layers.core.Activation object at 0x7f470cd86cc0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd48ac8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd018d0>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd408d0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd376d8>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470ccd96d8>, <layers.ResBlock object at 0x7f470cd374e0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd812e8>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd862e8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd302e8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd6def0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd40ef0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd30cf8>, <layers.ConvBlock object at 0x7f470cd01cf8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd28b00>, <layers.UpSampleConv object at 0x7f470cd6d908>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd1f908>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd6d710>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd5e710>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd77710>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470ccd9518>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd18518>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd5e518>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd67f28>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd5ef28>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd18f28>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd4ff28>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd86b38>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd48940>, <layers.ConvBlock object at 0x7f470ccd9940>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd48748>, <layers.ResBlock object at 0x7f470cd1f748>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd67550>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd5e358>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd13160>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd30160>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd5ed68>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470ccd9d68>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd30b70>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd57b70>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd30978>, <layers.ResBlock object at 0x7f470cd57978>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd4f780>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd48588>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd1f5f8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd77588>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd4f5f8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470ccf3390>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd18390>, <layers.ConvBlock object at 0x7f470cd81198>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd01f98>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd48f98>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd4f198>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd1ff98>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd67da0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd18da0>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd77da0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd40da0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd6dda0>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd18ba8>, <layers.ResBlock object at 0x7f470cd40ba8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd379b0>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd307b8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd137b8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd815c0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd673c8>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd373c8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd81fd0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd28fd0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd571d0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470ccf3dd8>, <layers.ResBlock object at 0x7f470cd28dd8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd77be0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470ccd9be0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd1fbe0>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd67be0>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd189e8>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd6d5f8>]\r\n\r\n**Additional info:**\r\n- Trained using --light (Supplying or not supplying --light generates same error) \r\n- Files in dir provided to m_path : checkpoint  generator-100.data-00000-of-00001  generator-100.index\r\n- Trained and executed on Google Colab"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/24",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/24/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/24/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/24/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/24",
        "id": 507000512,
        "node_id": "MDU6SXNzdWU1MDcwMDA1MTI=",
        "number": 24,
        "title": "environment install using pip ",
        "user": {
            "login": "Aacrobat",
            "id": 26108453,
            "node_id": "MDQ6VXNlcjI2MTA4NDUz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/26108453?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Aacrobat",
            "html_url": "https://github.com/Aacrobat",
            "followers_url": "https://api.github.com/users/Aacrobat/followers",
            "following_url": "https://api.github.com/users/Aacrobat/following{/other_user}",
            "gists_url": "https://api.github.com/users/Aacrobat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Aacrobat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Aacrobat/subscriptions",
            "organizations_url": "https://api.github.com/users/Aacrobat/orgs",
            "repos_url": "https://api.github.com/users/Aacrobat/repos",
            "events_url": "https://api.github.com/users/Aacrobat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Aacrobat/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-10-15T04:39:50Z",
        "updated_at": "2019-10-19T08:52:46Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "ERROR: tf-nightly-2-0-preview 2.0.0.dev20191002 has requirement gast==0.2.2, but you'll have gast 0.3.2 which is incompatible.\r\nERROR: tf-nightly-2-0-preview 2.0.0.dev20191002 has requirement numpy<2.0,>=1.16.0, but you'll have numpy 1.15.1 which is incompatible.\r\nERROR: tf-nightly-2-0-preview 2.0.0.dev20191002 has requirement tb-nightly<2.2.0a0,>=2.1.0a0, but you'll have tb-nightly 1.14.0a20190505 which is incompatible.\r\nERROR: tensorflow-gpu 2.0.0a0 has requirement tb-nightly<1.14.0a20190302,>=1.14.0a20190301, but you'll have tb-nightly 1.14.0a20190505 which is incompatible.\r\n\r\nwhen i use pip install requirement.txt the error occor"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/23",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/23/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/23/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/23/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/23",
        "id": 503297204,
        "node_id": "MDU6SXNzdWU1MDMyOTcyMDQ=",
        "number": 23,
        "title": "problem with environment_mac_cpu.yml",
        "user": {
            "login": "cindylee13",
            "id": 34035926,
            "node_id": "MDQ6VXNlcjM0MDM1OTI2",
            "avatar_url": "https://avatars3.githubusercontent.com/u/34035926?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/cindylee13",
            "html_url": "https://github.com/cindylee13",
            "followers_url": "https://api.github.com/users/cindylee13/followers",
            "following_url": "https://api.github.com/users/cindylee13/following{/other_user}",
            "gists_url": "https://api.github.com/users/cindylee13/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/cindylee13/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cindylee13/subscriptions",
            "organizations_url": "https://api.github.com/users/cindylee13/orgs",
            "repos_url": "https://api.github.com/users/cindylee13/repos",
            "events_url": "https://api.github.com/users/cindylee13/events{/privacy}",
            "received_events_url": "https://api.github.com/users/cindylee13/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-10-07T08:15:02Z",
        "updated_at": "2019-10-19T08:48:10Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "`conda env create -n cartoongan -f environment_mac_cpu.yml\r\n`\r\n\r\nand some errors happen\r\n> SpecNotFound: Invalid name, try the format: user/package\r\n\r\nI'm using a MacBook with anaconda3\r\nconda: 4.7.10\r\npip 18.1 from /home/comp/anaconda3/lib/python3.7/site-packages/pip\r\nI found some discussion about the instruction \"conda env create\" not working,\r\nbut I'm not sure if there's also problems with the yml document, thanks!"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/21",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/21/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/21/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/21/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/21",
        "id": 484701999,
        "node_id": "MDU6SXNzdWU0ODQ3MDE5OTk=",
        "number": 21,
        "title": "Error when run cartoonize.py",
        "user": {
            "login": "MNCTTY",
            "id": 37251686,
            "node_id": "MDQ6VXNlcjM3MjUxNjg2",
            "avatar_url": "https://avatars0.githubusercontent.com/u/37251686?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MNCTTY",
            "html_url": "https://github.com/MNCTTY",
            "followers_url": "https://api.github.com/users/MNCTTY/followers",
            "following_url": "https://api.github.com/users/MNCTTY/following{/other_user}",
            "gists_url": "https://api.github.com/users/MNCTTY/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MNCTTY/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MNCTTY/subscriptions",
            "organizations_url": "https://api.github.com/users/MNCTTY/orgs",
            "repos_url": "https://api.github.com/users/MNCTTY/repos",
            "events_url": "https://api.github.com/users/MNCTTY/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MNCTTY/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-08-23T20:36:54Z",
        "updated_at": "2019-10-27T08:17:22Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Hello! I tried to run simply cartoonize.py with all default arguments and faced this error:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"cartoonize.py\", line 371, in <module>\r\n    main()\r\n  File \"cartoonize.py\", line 355, in main\r\n    output_image = post_processing(transformed_image, style=style)\r\n  File \"cartoonize.py\", line 110, in post_processing\r\n    transformed_image = transformed_image.numpy()\r\nAttributeError: 'Tensor' object has no attribute 'numpy'\r\n```\r\n\r\nWhat it can be?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/20",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/20/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/20/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/20/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/20",
        "id": 474433105,
        "node_id": "MDU6SXNzdWU0NzQ0MzMxMDU=",
        "number": 20,
        "title": "Failed to load the pretrain model ",
        "user": {
            "login": "Govan111",
            "id": 23721413,
            "node_id": "MDQ6VXNlcjIzNzIxNDEz",
            "avatar_url": "https://avatars1.githubusercontent.com/u/23721413?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Govan111",
            "html_url": "https://github.com/Govan111",
            "followers_url": "https://api.github.com/users/Govan111/followers",
            "following_url": "https://api.github.com/users/Govan111/following{/other_user}",
            "gists_url": "https://api.github.com/users/Govan111/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Govan111/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Govan111/subscriptions",
            "organizations_url": "https://api.github.com/users/Govan111/orgs",
            "repos_url": "https://api.github.com/users/Govan111/repos",
            "events_url": "https://api.github.com/users/Govan111/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Govan111/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-07-30T07:59:23Z",
        "updated_at": "2019-08-05T08:29:28Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I fail to load the trained model to finetune, which is in the file of light_shinkai_ckpt. It shows that   \r\n\u2018Checkpoint is not found, training from scratch with 1 epochs...\u2019"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/17",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/17/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/17/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/17/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/17",
        "id": 462361752,
        "node_id": "MDU6SXNzdWU0NjIzNjE3NTI=",
        "number": 17,
        "title": "AttributeError: module 'tensorflow' has no attribute 'get_default_graph",
        "user": {
            "login": "WenheLI",
            "id": 23213772,
            "node_id": "MDQ6VXNlcjIzMjEzNzcy",
            "avatar_url": "https://avatars1.githubusercontent.com/u/23213772?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/WenheLI",
            "html_url": "https://github.com/WenheLI",
            "followers_url": "https://api.github.com/users/WenheLI/followers",
            "following_url": "https://api.github.com/users/WenheLI/following{/other_user}",
            "gists_url": "https://api.github.com/users/WenheLI/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/WenheLI/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/WenheLI/subscriptions",
            "organizations_url": "https://api.github.com/users/WenheLI/orgs",
            "repos_url": "https://api.github.com/users/WenheLI/repos",
            "events_url": "https://api.github.com/users/WenheLI/events{/privacy}",
            "received_events_url": "https://api.github.com/users/WenheLI/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-06-30T03:08:19Z",
        "updated_at": "2019-08-05T08:26:40Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Thanks for your excellent work!\r\nI got an error of `AttributeError: module 'tensorflow' has no attribute 'get_default_graph` when I try to run your code. It seems to be a dependency issue do you have any clue?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/16",
        "repository_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow",
        "labels_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/16/labels{/name}",
        "comments_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/16/comments",
        "events_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/16/events",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/16",
        "id": 454453237,
        "node_id": "MDU6SXNzdWU0NTQ0NTMyMzc=",
        "number": 16,
        "title": "convert",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-11T02:36:51Z",
        "updated_at": "2019-06-11T02:36:51Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I want convert\r\nstyle transform to\r\nHayao.pb  Hosoda.pb.......\r\nCan you help me?"
    }
]