[
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/38",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/38/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/38/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/38/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/38",
        "id": 544316444,
        "node_id": "MDU6SXNzdWU1NDQzMTY0NDQ=",
        "number": 38,
        "title": "Inclusion of other techniques",
        "user": {
            "login": "DonaldTsang",
            "id": 10583082,
            "node_id": "MDQ6VXNlcjEwNTgzMDgy",
            "avatar_url": "https://avatars1.githubusercontent.com/u/10583082?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/DonaldTsang",
            "html_url": "https://github.com/DonaldTsang",
            "followers_url": "https://api.github.com/users/DonaldTsang/followers",
            "following_url": "https://api.github.com/users/DonaldTsang/following{/other_user}",
            "gists_url": "https://api.github.com/users/DonaldTsang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/DonaldTsang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/DonaldTsang/subscriptions",
            "organizations_url": "https://api.github.com/users/DonaldTsang/orgs",
            "repos_url": "https://api.github.com/users/DonaldTsang/repos",
            "events_url": "https://api.github.com/users/DonaldTsang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/DonaldTsang/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-01-01T06:09:36Z",
        "updated_at": "2020-01-01T06:09:36Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Please take a look at https://github.com/ChaofWang/Awesome-Super-Resolution and https://github.com/YapengTian/Single-Image-Super-Resolution for other algorithms that you can implement in order to be complete.\r\n\r\nAlso other parts of interest:\r\n- https://github.com/xiaomi-automl/FALSR\r\n- https://github.com/huangzehao/Super-Resolution.Benckmark\r\n- https://github.com/jbhuang0604/SelfExSR\r\n- https://github.com/thstkdgus35/EDSR-PyTorch\r\n- https://github.com/yulunzhang/RCAN\r\n- https://github.com/limbee/NTIRE2017\r\n- https://github.com/yulunzhang/RDN\r\n- https://github.com/Paper99/SRFBN_CVPR19"
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/37",
        "id": 493213545,
        "node_id": "MDU6SXNzdWU0OTMyMTM1NDU=",
        "number": 37,
        "title": "Fix for newer Keras versions",
        "user": {
            "login": "progmars",
            "id": 4199737,
            "node_id": "MDQ6VXNlcjQxOTk3Mzc=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/4199737?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/progmars",
            "html_url": "https://github.com/progmars",
            "followers_url": "https://api.github.com/users/progmars/followers",
            "following_url": "https://api.github.com/users/progmars/following{/other_user}",
            "gists_url": "https://api.github.com/users/progmars/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/progmars/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/progmars/subscriptions",
            "organizations_url": "https://api.github.com/users/progmars/orgs",
            "repos_url": "https://api.github.com/users/progmars/repos",
            "events_url": "https://api.github.com/users/progmars/events{/privacy}",
            "received_events_url": "https://api.github.com/users/progmars/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-09-13T09:01:13Z",
        "updated_at": "2019-09-13T09:02:04Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "I got an error:\r\n`AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'`\r\n\r\nIf you want to support newer Keras, then according to this:\r\nhttps://github.com/keras-team/keras/issues/12649\r\nthe method has be renamed to image_data_format."
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/36",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/36/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/36/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/36/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/36",
        "id": 491443263,
        "node_id": "MDU6SXNzdWU0OTE0NDMyNjM=",
        "number": 36,
        "title": "where is the \"imgpath\"",
        "user": {
            "login": "lyn-sys",
            "id": 55123874,
            "node_id": "MDQ6VXNlcjU1MTIzODc0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/55123874?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lyn-sys",
            "html_url": "https://github.com/lyn-sys",
            "followers_url": "https://api.github.com/users/lyn-sys/followers",
            "following_url": "https://api.github.com/users/lyn-sys/following{/other_user}",
            "gists_url": "https://api.github.com/users/lyn-sys/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lyn-sys/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lyn-sys/subscriptions",
            "organizations_url": "https://api.github.com/users/lyn-sys/orgs",
            "repos_url": "https://api.github.com/users/lyn-sys/repos",
            "events_url": "https://api.github.com/users/lyn-sys/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lyn-sys/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-09-10T04:28:46Z",
        "updated_at": "2019-09-13T03:06:44Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "it is a directory or a file?"
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/35",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/35/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/35/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/35/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/35",
        "id": 420875286,
        "node_id": "MDU6SXNzdWU0MjA4NzUyODY=",
        "number": 35,
        "title": "How to get the Feature extraction effect map",
        "user": {
            "login": "winstonKang",
            "id": 43230479,
            "node_id": "MDQ6VXNlcjQzMjMwNDc5",
            "avatar_url": "https://avatars0.githubusercontent.com/u/43230479?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/winstonKang",
            "html_url": "https://github.com/winstonKang",
            "followers_url": "https://api.github.com/users/winstonKang/followers",
            "following_url": "https://api.github.com/users/winstonKang/following{/other_user}",
            "gists_url": "https://api.github.com/users/winstonKang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/winstonKang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/winstonKang/subscriptions",
            "organizations_url": "https://api.github.com/users/winstonKang/orgs",
            "repos_url": "https://api.github.com/users/winstonKang/repos",
            "events_url": "https://api.github.com/users/winstonKang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/winstonKang/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-03-14T07:51:50Z",
        "updated_at": "2019-03-14T07:51:50Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": ""
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/31",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/31/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/31/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/31/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/31",
        "id": 333048884,
        "node_id": "MDU6SXNzdWUzMzMwNDg4ODQ=",
        "number": 31,
        "title": "expected input_1 to have shape",
        "user": {
            "login": "ManoaNosea",
            "id": 7376591,
            "node_id": "MDQ6VXNlcjczNzY1OTE=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/7376591?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ManoaNosea",
            "html_url": "https://github.com/ManoaNosea",
            "followers_url": "https://api.github.com/users/ManoaNosea/followers",
            "following_url": "https://api.github.com/users/ManoaNosea/following{/other_user}",
            "gists_url": "https://api.github.com/users/ManoaNosea/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ManoaNosea/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ManoaNosea/subscriptions",
            "organizations_url": "https://api.github.com/users/ManoaNosea/orgs",
            "repos_url": "https://api.github.com/users/ManoaNosea/repos",
            "events_url": "https://api.github.com/users/ManoaNosea/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ManoaNosea/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2018-06-17T09:23:31Z",
        "updated_at": "2018-06-17T09:24:43Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\u03bb python tests_dsr.py\r\nUsing TensorFlow backend.\r\nTraining model : DenoisingAutoEncoderSR\r\n2018-06-17 08:36:39.645569: I T:\\src\\github\\tensorflow\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nEpoch 1/250\r\nFound 11156 images.\r\nTraceback (most recent call last):\r\n  File \"tests_dsr.py\", line 63, in <module>\r\n    dsr.fit(nb_epochs=250)\r\n  File \"Y:\\theshitt-backup\\Projects\\AINeuralNetSuperRes\\titu1994\\Image-Super-Resolution-master\\models.py\", line 607, in fit\r\n    return super(DenoisingAutoEncoderSR, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\n  File \"Y:\\theshitt-backup\\Projects\\AINeuralNetSuperRes\\titu1994\\Image-Super-Resolution-master\\models.py\", line 122, in fit\r\n    validation_steps=val_count // batch_size + 1)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training.py\", line 1426, in fit_generator\r\n    initial_epoch=initial_epoch)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training_generator.py\", line 191, in fit_generator\r\n    class_weight=class_weight)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training.py\", line 1214, in train_on_batch\r\n    class_weight=class_weight)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training.py\", line 754, in _standardize_user_data\r\n    exception_prefix='input')\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training_utils.py\", line 136, in standardize_input_data\r\n    str(data_shape))\r\nValueError: Error when checking input: expected input_1 to have shape (32, 32, 3) but got array with shape (64, 64, 3)"
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/27",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/27/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/27/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/27/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/27",
        "id": 318394824,
        "node_id": "MDU6SXNzdWUzMTgzOTQ4MjQ=",
        "number": 27,
        "title": "ValueError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].",
        "user": {
            "login": "wangtong627",
            "id": 37677851,
            "node_id": "MDQ6VXNlcjM3Njc3ODUx",
            "avatar_url": "https://avatars0.githubusercontent.com/u/37677851?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wangtong627",
            "html_url": "https://github.com/wangtong627",
            "followers_url": "https://api.github.com/users/wangtong627/followers",
            "following_url": "https://api.github.com/users/wangtong627/following{/other_user}",
            "gists_url": "https://api.github.com/users/wangtong627/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wangtong627/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wangtong627/subscriptions",
            "organizations_url": "https://api.github.com/users/wangtong627/orgs",
            "repos_url": "https://api.github.com/users/wangtong627/repos",
            "events_url": "https://api.github.com/users/wangtong627/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wangtong627/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 9,
        "created_at": "2018-04-27T12:40:59Z",
        "updated_at": "2018-05-27T06:15:34Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "i got this error while doing the testing,\r\n\r\n\r\nTraceback (most recent call last):\r\n  File \"main.py\", line 57, in <module>\r\n    model.upscale(p, save_intermediate=save, mode=mode, patch_size=patch_size, suffix=suffix)\r\n  File \"C:\\Users\\Administrator\\Desktop\\Image-Super-Resolution-master\\models.py\", line 202, in upscale\r\n    model = self.create_model(img_dim_2, img_dim_1, load_weights=True)\r\n  File \"C:\\Users\\Administrator\\Desktop\\Image-Super-Resolution-master\\models.py\", line 601, in create_model\r\n    if load_weights: model.load_weights(self.weight_path)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\keras\\engine\\topology.py\", line 2656, in load_weights\r\n    f, self.layers, reshape=reshape)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\keras\\engine\\topology.py\", line 3382, in load_weights_from_hdf5_group\r\n    K.batch_set_value(weight_value_tuples)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 2368, in batch_set_value\r\n    assign_op = x.assign(assign_placeholder)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 516, in assign\r\n    return state_ops.assign(self._variable, value, use_locking=use_locking)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\state_ops.py\", line 271, in assign\r\n    validate_shape=validate_shape)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\gen_state_ops.py\", line 45, in assign\r\n    use_locking=use_locking, name=name)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 767, in apply_op\r\n    op_def=op_def)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2508, in create_op\r\n    set_shapes_for_outputs(ret)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1873, in set_shapes_for_outputs\r\n    shapes = shape_func(op)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1823, in call_with_requiring\r\n    return call_cpp_shape_fn(op, require_shape_fn=True)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 610, in call_cpp_shape_fn\r\n    debug_python_shape_fn, require_shape_fn)\r\n  File \"E:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 676, in _call_cpp_shape_fn_impl\r\n    raise ValueError(err.message)\r\nValueError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].\r\n"
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/26",
        "id": 312907778,
        "node_id": "MDU6SXNzdWUzMTI5MDc3Nzg=",
        "number": 26,
        "title": "ValueError",
        "user": {
            "login": "Kazusasukina",
            "id": 28039210,
            "node_id": "MDQ6VXNlcjI4MDM5MjEw",
            "avatar_url": "https://avatars0.githubusercontent.com/u/28039210?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Kazusasukina",
            "html_url": "https://github.com/Kazusasukina",
            "followers_url": "https://api.github.com/users/Kazusasukina/followers",
            "following_url": "https://api.github.com/users/Kazusasukina/following{/other_user}",
            "gists_url": "https://api.github.com/users/Kazusasukina/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Kazusasukina/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Kazusasukina/subscriptions",
            "organizations_url": "https://api.github.com/users/Kazusasukina/orgs",
            "repos_url": "https://api.github.com/users/Kazusasukina/repos",
            "events_url": "https://api.github.com/users/Kazusasukina/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Kazusasukina/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2018-04-10T12:49:15Z",
        "updated_at": "2019-12-25T06:32:38Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "$ python main.py \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\results\\lenna.bmp\" --model=ddsr\r\nD:\\environment\\python\\python35\\lib\\site-packages\\h5py\\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\r\n  from ._conv import register_converters as _register_converters\r\nUsing TensorFlow backend.\r\nOld Size :  (512, 512, 3)\r\nNew Size : (1024, 1024, 3)\r\nNumber of patches = 1034289, Patch Shape = (8, 8)\r\nSaving intermediate image.\r\nTraceback (most recent call last):\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 686, in _call_cpp_shape_fn_impl\r\n    input_tensors_as_shapes, status)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\errors_impl.py\", line 473, in __exit__\r\n    c_api.TF_GetCode(self.status.status))\r\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"main.py\", line 57, in <module>\r\n    model.upscale(p, save_intermediate=save, mode=mode, patch_size=patch_size, suffix=suffix)\r\n  File \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\models.py\", line 202, in upscale\r\n    model = self.create_model(img_dim_2, img_dim_1, load_weights=True)\r\n  File \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\models.py\", line 659, in create_model\r\n    if load_weights: model.load_weights(self.weight_path)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\engine\\topology.py\", line 2656, in load_weights\r\n    f, self.layers, reshape=reshape)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\engine\\topology.py\", line 3382, in load_weights_from_hdf5_group\r\n    K.batch_set_value(weight_value_tuples)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 2368, in batch_set_value\r\n    assign_op = x.assign(assign_placeholder)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 573, in assign\r\n    return state_ops.assign(self._variable, value, use_locking=use_locking)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\state_ops.py\", line 276, in assign\r\n    validate_shape=validate_shape)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\gen_state_ops.py\", line 56, in assign\r\n    use_locking=use_locking, name=name)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\r\n    op_def=op_def)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2958, in create_op\r\n    set_shapes_for_outputs(ret)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2209, in set_shapes_for_outputs\r\n    shapes = shape_func(op)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2159, in call_with_requiring\r\n    return call_cpp_shape_fn(op, require_shape_fn=True)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 627, in call_cpp_shape_fn\r\n    require_shape_fn)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 691, in _call_cpp_shape_fn_impl\r\n    raise ValueError(err.message)\r\nValueError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].\r\n\r\nI  came across this problem and had no idea about how to figure this out @titu1994 ,may you help~ thanks"
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
        "id": 312861051,
        "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
        "number": 25,
        "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
        "user": {
            "login": "shreyaspalve",
            "id": 29245769,
            "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
            "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shreyaspalve",
            "html_url": "https://github.com/shreyaspalve",
            "followers_url": "https://api.github.com/users/shreyaspalve/followers",
            "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
            "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
            "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
            "repos_url": "https://api.github.com/users/shreyaspalve/repos",
            "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 7,
        "created_at": "2018-04-10T10:20:53Z",
        "updated_at": "2019-08-26T09:17:56Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/23",
        "id": 304488708,
        "node_id": "MDU6SXNzdWUzMDQ0ODg3MDg=",
        "number": 23,
        "title": "Requirements",
        "user": {
            "login": "impactcolor",
            "id": 4460178,
            "node_id": "MDQ6VXNlcjQ0NjAxNzg=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/4460178?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/impactcolor",
            "html_url": "https://github.com/impactcolor",
            "followers_url": "https://api.github.com/users/impactcolor/followers",
            "following_url": "https://api.github.com/users/impactcolor/following{/other_user}",
            "gists_url": "https://api.github.com/users/impactcolor/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/impactcolor/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/impactcolor/subscriptions",
            "organizations_url": "https://api.github.com/users/impactcolor/orgs",
            "repos_url": "https://api.github.com/users/impactcolor/repos",
            "events_url": "https://api.github.com/users/impactcolor/events{/privacy}",
            "received_events_url": "https://api.github.com/users/impactcolor/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 10,
        "created_at": "2018-03-12T18:26:44Z",
        "updated_at": "2018-06-12T00:21:42Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Hi is there any doc on requirements?  I'm running tensor flow with keras and I get errors on both python 2.7 and python 3.5.\r\n\r\nAny help would be appreciated, thank you!"
    },
    {
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/22",
        "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
        "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/22/labels{/name}",
        "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/22/comments",
        "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/22/events",
        "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/22",
        "id": 297350610,
        "node_id": "MDU6SXNzdWUyOTczNTA2MTA=",
        "number": 22,
        "title": "Train with own dataset",
        "user": {
            "login": "RaminAbbaszadi",
            "id": 15646332,
            "node_id": "MDQ6VXNlcjE1NjQ2MzMy",
            "avatar_url": "https://avatars2.githubusercontent.com/u/15646332?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/RaminAbbaszadi",
            "html_url": "https://github.com/RaminAbbaszadi",
            "followers_url": "https://api.github.com/users/RaminAbbaszadi/followers",
            "following_url": "https://api.github.com/users/RaminAbbaszadi/following{/other_user}",
            "gists_url": "https://api.github.com/users/RaminAbbaszadi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/RaminAbbaszadi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/RaminAbbaszadi/subscriptions",
            "organizations_url": "https://api.github.com/users/RaminAbbaszadi/orgs",
            "repos_url": "https://api.github.com/users/RaminAbbaszadi/repos",
            "events_url": "https://api.github.com/users/RaminAbbaszadi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/RaminAbbaszadi/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2018-02-15T07:25:01Z",
        "updated_at": "2018-02-15T07:25:01Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "Dear Titu,\r\nThank you for sharing your source code. I try to train your code with my own dataset which include images with size 128*64. But I get a same error in most of train model in test.py. \r\nerror:\r\nValueError: \r\nUsing TensorFlow backend.\r\nTraining model : ImageSuperResolutionModel\r\n2018-02-15 09:17:35.000003: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.\r\n2018-02-15 09:17:35.000047: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.\r\n2018-02-15 09:17:35.000061: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.\r\n2018-02-15 09:17:35.214561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties:\r\nname: GeForce GTX TITAN X\r\nmajor: 5 minor: 2 memoryClockRate (GHz) 1.076\r\npciBusID 0000:19:00.0\r\nTotal memory: 11.92GiB\r\nFree memory: 3.33GiB\r\n2018-02-15 09:17:35.214608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0\r\n2018-02-15 09:17:35.214622: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y\r\n2018-02-15 09:17:35.214644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:19:00.0)\r\nEpoch 1/250\r\nFound 51744 images.\r\nTraceback (most recent call last):\r\n  File \"tests.py\", line 47, in <module>\r\n    sr.fit(nb_epochs=250)\r\n  File \"/mnt/home/ramin/srcnn-org-codes/org/Image-Super-Resolution/models.py\", line 516, in fit\r\n    return super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\n  File \"/mnt/home/ramin/srcnn-org-codes/org/Image-Super-Resolution/models.py\", line 122, in fit\r\n    validation_steps=val_count // batch_size + 1)\r\n  File \"/mnt/home/ramin/Image-Super-Resolution/superRe/lib/python3.4/site-packages/keras/legacy/interfaces.py\", line 87, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"/mnt/home/ramin/Image-Super-Resolution/superRe/lib/python3.4/site-packages/keras/engine/training.py\", line 2115, in fit_generator\r\n    generator_output = next(output_generator)\r\n  File \"/mnt/home/ramin/Image-Super-Resolution/superRe/lib/python3.4/site-packages/keras/utils/data_utils.py\", line 735, in get\r\n    six.reraise(value.__class__, value, value.__traceback__)\r\n  File \"/mnt/home/ramin/Image-Super-Resolution/superRe/lib/python3.4/site-packages/six.py\", line 693, in reraise\r\n    raise value\r\n  File \"/mnt/home/ramin/Image-Super-Resolution/superRe/lib/python3.4/site-packages/keras/utils/data_utils.py\", line 635, in data_generator_task\r\n    generator_output = next(self._generator)\r\n  File \"/mnt/home/ramin/srcnn-org-codes/org/Image-Super-Resolution/img_utils.py\", line 303, in image_generator\r\n    batch_x[i] = img\r\nValueError: could not broadcast input array from shape (16,16,3) into shape (64,64,3)\r\nException ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7fe3e2aa9d68>>\r\nTraceback (most recent call last):\r\n  File \"/mnt/home/ramin/Image-Super-Resolution/superRe/lib/python3.4/site-packages/tensorflow/python/client/session.py\", line 587, in __del__\r\nTypeError: 'NoneType' object is not callable\r\n\r\n\r\nI am very appreciate from you, if you help me about it. \r\nThank you,\r\nRamin\r\n"
    }
]